projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: 'http://localhost:4000'
  prisma:
    schemaPath: datamodel.1585770106306.prisma
    extensions:
      prisma: prisma.yml
extensions:
  amplify:
    version: 3
