/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5b989ce9-119e-45bb-99f8-1ecffa349e45",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_RfvJfJ5XB",
    "aws_user_pools_web_client_id": "638jlcd3ai0ljt49fnfd4i78ct",
    "oauth": {
        "domain": "lakeviewpets-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
